### ISSUE TITLE
I can not find the defination of variable 'NN_size'.

### ISSUE THREAD

**Issue by hwpengTristin** [kolak33/SRWGANGP#2]
I can not find the defination of variable 'NN_size' in the function 'process_and_save_images' of the script 'srwgangp_threaded.py' 

Variable 'NN_size'  Location in the script 'srwgangp_threaded.py' :

	def process_and_save_images(self, save_directory, save_directory_nearest, save_directory_hr, file_path_test_list_lr, file_path_test_list_hr, 
								save_nearest_neighbour=False, save_hr=False):
		batch_test_32, batch_test_128 = self.get_batch_test_imgs(file_path_test_list_lr, file_path_test_list_hr)

		predicted_128 = self.generator_model_valid.predict_on_batch(batch_test_32)

		[_, predicted_128, _] = predicted_128

		PSNR_batch_test = self.PSNR_test_array(y_true=batch_test_128, y_pred=predicted_128)
		
		images_predicted = self.denormalize_batch_images(predicted_128)
		self.save_batch_images(directory=save_directory, psnr_batch=PSNR_batch_test, image_batch=images_predicted)
		
		if save_nearest_neighbour:
			batch_test_32 = self.denormalize_batch_images(batch_test_32)
			batch_128_nearest = []
			for i in range(self.BATCH_SIZE):
				img = misc.imresize(batch_test_32[i], **### NN_size**, interp="nearest")
				batch_128_nearest.append(img)

**Comment by kolak33** [comment]
There should be DOWNSCALE_FACTOR variable from config file: config_srwgangp_threaded.py. I've fixed it.
